apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollout-deployment
  labels:
    app: rollout
spec:
  replicas: 5
  selector:
    matchLabels:
      app: rollout
  template:
    metadata:
      labels:
        app: rollout
    spec:
      containers:
      - name: rollout
        image: toleksa/kube-rollout:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: rollout-service
spec:
  selector:
    app: rollout
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rollout-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: rollout.kube.ac
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rollout-service
            port: 
              number: 80
